enum CHANGE_LOCALE {PENDING, SUCCESS, ERROR}
enum GET_AUTH_ORGS {PENDING, SUCCESS, ERROR}
enum GET_AUTH_STAR_COUNT {PENDING, SUCCESS, ERROR}
enum GET_AUTH_USER {PENDING, SUCCESS, ERROR}
enum GET_EVENTS {PENDING, SUCCESS, ERROR}
enum LOGIN {PENDING, SUCCESS, ERROR}
enum LOGOUT {PENDING, SUCCESS, ERROR}